name: Backend CI Pipeline

on:
  push:
    paths:
      - "backend/**"
    

permissions:
  id-token: write
  contents: write

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run EsLint
        working-directory: ./backend
        run: npm run lint

      - name: Run Dependency Scan
        working-directory: ./backend
        run: npm run audit --audit-level=high

      - name: Build Backend Docker Image
        run: |
          docker build \
          -t jerney-backend:latest \
          ./backend

      - name: Scan Backend Docker Image
        uses: aquasecurity/trivy-action@0.36.1
        with:
          image-ref: jerney-backend:latest
          severity: HIGH,CRITICAL
          exit-code: "1"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Backend Docker Image
        run: |
            docker tag jerney-backend:latest \
            ${{secrets.BACKEND_ECR_URI}}:${{github.sha}}

      - name: Push Backend Docker Image
        run: |
            docker push \
             ${{ secrets.BACKEND_ECR_URI }}:${{ github.sha }}
   
      - name: Update Kubernetes Manifest
        run: |
          sed -i \
          "s|image:.*|image: ${{ secrets.BACKEND_ECR_URI }}:${{github.sha}}|"\
          k8s/backend/deployment.yaml

      - name: Commit Manifest Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email \
          "github-actions@github.com"
          git add k8s/backend/deployment.yaml
          git commit -m \
          "update backend image tag" || true

      - name: Push Changes
        run: |
          git push
